name: Python Code Format and Sort Imports

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort
    - name: Analysing the code with black
      uses: psf/black@stable
      with:
        options: --check --diff --verbose
        src: .
    - name: Format the code with black
      if: failure()
      run: |
        black ./
